<?php

namespace App\Traits;

use App\Helpers\FormRequestHelper;

trait GeneratesLetterAttributes
{
    /**
     * Generate human-readable attributes for dynamic arrays (copies, resources, etc.)
     * and merge them with the standard static attribute labels.
     *
     * @param array $data The input data (e.g. $request->all() or prepared data)
     * @param array $rules The validation rules array
     * @return array
     */
    protected function generateLetterAttributes(array $data, array $rules): array
    {
        // Get standard static attributes
        $attributes = FormRequestHelper::mapAttributeLabelsFromRules($rules);

        // REMOVE wildcard attributes generated by the helper (e.g. copies.*.archive)
        // This prevents the Validator from matching "copies.0.archive" to the generic
        // "hiko.copies.*.archive" label, ensuring it uses our specific labels below.
        foreach ($attributes as $key => $value) {
            if (str_contains($key, '*')) {
                unset($attributes[$key]);
            }
        }

        // Generate dynamic attributes for 'copies'
        if (isset($data['copies']) && is_array($data['copies'])) {
            $labelManifestation = __('hiko.manifestation_location');

            foreach ($data['copies'] as $index => $copy) {
                $position = $index + 1;
                $prefix = "{$labelManifestation} #{$position}";

                $attributes["copies.{$index}.archive"] = "{$prefix} – " . __('hiko.archive');
                $attributes["copies.{$index}.collection"] = "{$prefix} – " . __('hiko.collection');
                $attributes["copies.{$index}.repository"] = "{$prefix} – " . __('hiko.repository');
                $attributes["copies.{$index}.signature"] = "{$prefix} – " . __('hiko.signature');
                $attributes["copies.{$index}.l_number"] = "{$prefix} – " . __('hiko.l_number');
                $attributes["copies.{$index}.copy"] = "{$prefix} – " . __('hiko.doc_mode');
                $attributes["copies.{$index}.type"] = "{$prefix} – " . __('hiko.doc_type');
                $attributes["copies.{$index}.preservation"] = "{$prefix} – " . __('hiko.preservation');
                $attributes["copies.{$index}.manifestation_notes"] = "{$prefix} – " . __('hiko.manifestation_notes');
                $attributes["copies.{$index}.location_note"] = "{$prefix} – " . __('hiko.location_note');
            }
        }

        // Generate dynamic attributes for 'related_resources'
        if (isset($data['related_resources']) && is_array($data['related_resources'])) {
            $labelResource = __('hiko.related_resources');

            foreach ($data['related_resources'] as $index => $resource) {
                $position = $index + 1;
                $prefix = "{$labelResource} #{$position}";

                $attributes["related_resources.{$index}.title"] = "{$prefix} – " . __('hiko.name_2');
                $attributes["related_resources.{$index}.link"] = "{$prefix} – URL";
            }
        }

        // Generate dynamic attributes for Relationships (Authors, etc.)
        $relations = ['authors', 'recipients', 'mentioned', 'origins', 'destinations', 'keywords'];

        foreach ($relations as $relation) {
            if (isset($data[$relation]) && is_array($data[$relation])) {
                // Convert plural key (authors) to singular translation key (hiko.author)
                $key = rtrim($relation, 's');
                $groupLabel = __("hiko.{$key}");

                foreach ($data[$relation] as $index => $item) {
                    $position = $index + 1;
                    $attributes["{$relation}.{$index}.id"] = "{$groupLabel} #{$position}";
                    $attributes["{$relation}.{$index}.value"] = "{$groupLabel} #{$position}";
                    $attributes["{$relation}.{$index}"] = "{$groupLabel} #{$position}";
                }
            }
        }

        return $attributes;
    }
}
