<x-app-layout :title="$title">
    <x-success-alert />

    @if($errors->any())
        <div class="max-w-7xl mx-auto mb-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded">
            <h3 class="font-bold mb-2">{{ __('hiko.validation_errors') }}</h3>
            <ul class="list-disc list-inside">
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(session('error'))
        <div class="max-w-7xl mx-auto mb-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded">
            {{ session('error') }}
        </div>
    @endif

    <div class="max-w-7xl mx-auto"
         x-data="{
            criteria: @js($criteria ?? config('global_place_merge.default_criteria')),
            nameSimilarityThreshold: @js($nameSimilarityThreshold ?? config('global_place_merge.name_similarity_threshold')),
            latitudeTolerance: @js($latitudeTolerance ?? config('global_place_merge.latitude_tolerance')),
            longitudeTolerance: @js($longitudeTolerance ?? config('global_place_merge.longitude_tolerance')),
            countryAndNameThreshold: @js($countryAndNameThreshold ?? config('global_place_merge.country_and_name_threshold')),
            isLoading: false,
            submitLoading: false,
            showGuide: false,
            showConfig: @js(request()->has('criteria') ? false : true),

            updatePreview() {
                if (this.criteria.length === 0) {
                    alert(@js(__('hiko.at_least_one_criterion_required')));
                    return;
                }
                this.isLoading = true;
                setTimeout(() => {
                    const params = new URLSearchParams();
                    this.criteria.forEach(c => params.append('criteria[]', c));
                    params.append('name_similarity_threshold', this.nameSimilarityThreshold);
                    params.append('latitude_tolerance', this.latitudeTolerance);
                    params.append('longitude_tolerance', this.longitudeTolerance);
                    params.append('country_and_name_threshold', this.countryAndNameThreshold);
                    window.location.href = '{{ route("places.global-merge") }}?' + params.toString();
                }, 50);
            },

            submitForm() {
                if (this.submitLoading) return;

                if (this.criteria.length === 0) {
                    alert(@js(__('hiko.at_least_one_criterion_required')));
                    return;
                }

                // Check for hidden inputs generated by Livewire
                const selectedPlacesInputs = document.querySelectorAll('input[name=\'selected_places[]\']');
                if (selectedPlacesInputs.length === 0) {
                    alert(@js(__('hiko.at_least_one_place_required')));
                    return;
                }

                if (!confirm(@js(__('hiko.confirm_execute_merge')))) {
                    return;
                }

                this.submitLoading = true;
                this.$refs.mergeForm.submit();
            }
         }"
    >
        <div class="mb-6 flex justify-between">
            <a href="{{ route('places') }}" class="text-sm text-gray-600 hover:text-gray-900 flex items-center gap-1">
                <span>←</span> {{ __('hiko.back_to_places') }}
            </a>
            <button @click="showGuide = !showGuide" type="button" class="text-sm font-semibold text-primary hover:underline flex items-center gap-1">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                {{ __('hiko.guide') }}
            </button>
        </div>

        <div x-show="showGuide" x-transition class="mb-6 bg-blue-50 border border-blue-200 rounded-md p-4 relative" style="display: none;">
            <button @click="showGuide = false" class="absolute top-2 right-9 text-blue-400 hover:text-blue-600">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
            </button>
            <h3 class="text-sm font-bold text-blue-800">{{ __('hiko.how_to_merge') }}</h3>
            <ul class="list-disc list-inside text-sm text-blue-700 mt-2">
                {{-- Note: You may want to create specific translation keys for Global Merge steps later --}}
                <li>{{ __('hiko.global_merge_step_1') ?? 'Choose criteria to match local places with existing global places.' }}</li>
                <li>{{ __('hiko.global_merge_step_2') ?? 'Review the preview table. Items marked "Merge" will update a global place. Items marked "Move" will become new global places.' }}</li>
                <li>{{ __('hiko.global_merge_step_3') ?? 'Select the places you wish to process and click "Execute Merge".' }}</li>
            </ul>
        </div>

        {{-- Merging Criteria Configuration --}}
        <div x-show="showConfig" x-transition class="bg-white shadow-sm rounded-lg p-6 mb-6 relative">
            {{-- Loading Overlay for Criteria Update --}}
            <div x-show="isLoading" x-transition.opacity
                 class="absolute inset-0 bg-white bg-opacity-60 z-10 flex items-center justify-center rounded-lg"
                 style="display: none;">
                <div class="flex flex-col items-center p-4 bg-white shadow-lg rounded-full">
                    <svg class="animate-spin h-8 w-8 text-gray-800" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                </div>
            </div>

            <h2 class="text-xl font-semibold mb-4">{{ __('hiko.merging_criteria') }}</h2>
            <p class="text-sm text-gray-600 mb-4">{{ __('hiko.global_place_merging_criteria_description') }}</p>

            @if(session('criteria_error'))
                <div class="mb-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded">
                    {{ session('criteria_error') }}
                </div>
            @endif

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <label class="flex items-start p-3 border rounded hover:bg-gray-50 cursor-pointer">
                    <input
                        type="checkbox"
                        value="geoname_id"
                        x-model="criteria"
                        class="mt-1 mr-1 rounded border-gray-300">
                    <div>
                        <div class="font-medium">{{ __('hiko.merge_by_geoname_id') }}</div>
                        <div class="text-sm text-gray-600">{{ __('hiko.merge_by_geoname_id_desc') }}</div>
                    </div>
                </label>

                <label class="flex items-start p-3 border rounded hover:bg-gray-50 cursor-pointer">
                    <input
                        type="checkbox"
                        value="alternative_names"
                        x-model="criteria"
                        class="mt-1 mr-1 rounded border-gray-300">
                    <div>
                        <div class="font-medium">{{ __('hiko.merge_by_alternative_names') }}</div>
                        <div class="text-sm text-gray-600">{{ __('hiko.merge_by_alternative_names_desc') }}</div>
                    </div>
                </label>

                <label class="flex items-start p-3 border rounded hover:bg-gray-50 cursor-pointer">
                    <input
                        type="checkbox"
                        value="name_similarity"
                        x-model="criteria"
                        class="mt-1 mr-1 rounded border-gray-300">
                    <div class="flex-1">
                        <div class="font-medium">{{ __('hiko.merge_by_name_similarity') }}</div>
                        <div class="text-sm text-gray-600">{{ __('hiko.merge_by_name_similarity_desc') }}</div>
                        <div x-show="criteria.includes('name_similarity')" class="mt-2">
                            <label class="flex items-center">
                                <span class="text-sm mr-2">{{ __('hiko.threshold') }}:</span>
                                <input
                                    type="number"
                                    x-model="nameSimilarityThreshold"
                                    min="0"
                                    max="100"
                                    class="w-20 px-2 py-1 border rounded text-sm">
                                <span class="text-sm ml-1">%</span>
                            </label>
                        </div>
                    </div>
                </label>

                <label class="flex items-start p-3 border rounded hover:bg-gray-50 cursor-pointer">
                    <input
                        type="checkbox"
                        value="coordinates"
                        x-model="criteria"
                        class="mt-1 mr-1 rounded border-gray-300">
                    <div class="flex-1">
                        <div class="font-medium">{{ __('hiko.merge_by_coordinates') }}</div>
                        <div class="text-sm text-gray-600">{{ __('hiko.merge_by_coordinates_desc') }}</div>
                        <div x-show="criteria.includes('coordinates')" class="mt-2 space-y-2">
                            <label class="flex items-center">
                                <span class="text-sm mr-2 w-24">{{ __('hiko.latitude_abbr') }}:</span>
                                <input
                                    type="number"
                                    x-model="latitudeTolerance"
                                    step="0.001"
                                    min="0"
                                    class="w-24 px-2 py-1 border rounded text-sm">
                                <span class="text-sm ml-1">{{ __('hiko.tolerance') }}</span>
                            </label>
                            <label class="flex items-center">
                                <span class="text-sm mr-2 w-24">{{ __('hiko.longitude_abbr') }}:</span>
                                <input
                                    type="number"
                                    x-model="longitudeTolerance"
                                    step="0.001"
                                    min="0"
                                    class="w-24 px-2 py-1 border rounded text-sm">
                                <span class="text-sm ml-1">{{ __('hiko.tolerance') }}</span>
                            </label>
                        </div>
                    </div>
                </label>

                <label class="flex items-start p-3 border rounded hover:bg-gray-50 cursor-pointer">
                    <input
                        type="checkbox"
                        value="country_and_name"
                        x-model="criteria"
                        class="mt-1 mr-1 rounded border-gray-300">
                    <div class="flex-1">
                        <div class="font-medium">{{ __('hiko.merge_by_country_and_name') }}</div>
                        <div class="text-sm text-gray-600">{{ __('hiko.merge_by_country_and_name_desc') }}</div>
                        <div x-show="criteria.includes('country_and_name')" class="mt-2">
                            <label class="flex items-center">
                                <span class="text-sm mr-2">{{ __('hiko.threshold') }}:</span>
                                <input
                                    type="number"
                                    x-model="countryAndNameThreshold"
                                    min="0"
                                    max="100"
                                    class="w-20 px-2 py-1 border rounded text-sm">
                                <span class="text-sm ml-1">%</span>
                            </label>
                        </div>
                    </div>
                </label>
            </div>

            <div class="mt-6 flex justify-center">
                <button
                    type="button"
                    @click="updatePreview()"
                    :disabled="isLoading"
                    class="px-4 py-2 mt-4 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 disabled:opacity-25 disabled:cursor-not-allowed transition ease-in-out duration-150 flex items-center gap-2">
                    <svg x-show="isLoading" class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" style="display: none;">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span x-text="isLoading ? '{{ __('hiko.loading') }}...' : '{{ __('hiko.update_preview') }}'"></span>
                </button>
            </div>
        </div>

        <div x-show="!showConfig" class="mb-4">
            <button @click="showConfig = true" type="button" class="text-sm text-gray-600 hover:text-gray-900 flex items-center gap-1">
                ← {{ __('hiko.change_criteria') }}
            </button>
        </div>

        {{-- Preview Table with Form --}}
        <form x-ref="mergeForm" method="POST" action="{{ route('places.global-merge.execute') }}">
            @csrf

            {{-- Hidden inputs for criteria and thresholds --}}
            <template x-for="criterion in criteria" :key="criterion">
                <input type="hidden" name="criteria[]" :value="criterion">
            </template>
            <input type="hidden" name="name_similarity_threshold" :value="nameSimilarityThreshold">
            <input type="hidden" name="latitude_tolerance" :value="latitudeTolerance">
            <input type="hidden" name="longitude_tolerance" :value="longitudeTolerance">
            <input type="hidden" name="country_and_name_threshold" :value="countryAndNameThreshold">

            <div class="bg-white shadow-sm rounded-lg p-6 mb-6">
                <h2 class="text-xl font-semibold mb-4">{{ __('hiko.preview') }}</h2>

                <livewire:global-place-merge-preview
                    :criteria="$criteria ?? config('global_place_merge.default_criteria')"
                    :nameSimilarityThreshold="$nameSimilarityThreshold ?? config('global_place_merge.name_similarity_threshold')"
                    :latitudeTolerance="$latitudeTolerance ?? config('global_place_merge.latitude_tolerance')"
                    :longitudeTolerance="$longitudeTolerance ?? config('global_place_merge.longitude_tolerance')"
                    :countryAndNameThreshold="$countryAndNameThreshold ?? config('global_place_merge.country_and_name_threshold')"
                />
            </div>

            <div class="flex items-center justify-end">
                <button
                    type="button"
                    @click.prevent="submitForm()"
                    :disabled="submitLoading"
                    class="relative flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-primary rounded hover:bg-black disabled:opacity-50 transition-all duration-300 ease-in-out">
                    <svg x-show="submitLoading" class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" style="display: none;">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span x-show="!submitLoading">{{ __('hiko.execute_merge') }}</span>
                    <span x-show="submitLoading" style="display: none;">{{ __('hiko.loading') }}...</span>
                </button>
            </div>
        </form>
    </div>
</x-app-layout>
